# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Java release used to compile (8 for 1.16, 17 for 1.19-1.20, 21 for 1.21+)
java_release=16

# Mixin compatibility level (JAVA_8 / JAVA_17 / JAVA_21)
mixin_compatibility_level=JAVA_16

# Fabric API
fabric_api_version=0.141.3+1.21.11

# Mod Properties
mod_version=1.0.0
maven_group=net.ded3ec
archives_base_name=authcore

# Dependencies
sqlite_version=3.51.1.0
mysql_version=9.5.0
postgres_version=42.7.5
jedis_version=5.2.0
commons_pool2_version=2.12.0
fabric_permissions_version=0.6.1
gson_version=2.13.2
kotlin_version=2.2.20
configurate_core_version=4.2.0
configurate_hocon_version=4.2.0
password4j_version=1.8.4
floodgate_version=+

bouncycastle_version=1.78.1
