// ============================================================================
// AuthCore - multi-loader / multi-version build workspace.
//
// Toolchain: Stonecraft (Stonecutter + Architectury Loom + Mod-Publish-Plugin)
//
// One source tree (src/main/java, Mojang mappings) is compiled per
// "version group" x "loader" variant. Each variant is a small Gradle project
// generated by Stonecutter into versions/<mc>-<loader>/ and configured by the
// central build.gradle.kts. Version-specific differences in code are handled
// by Stonecutter preprocessor comments, e.g.:
//
//   /*? if < 1.19 {*/
//   ... old code ...
//   /*?} else {*/
//   ... new code ...
//   /*?}*/
//
// Version groups (one released jar per group):
//   G1  1.16 - 1.18  (build target 1.18.2, intermediary era)
//   G2  1.19 - 1.21  (build target 1.21.11, intermediary era)
//   G3  26.1-26.2         (build target 26.2, unobfuscated / Mojang names)
// ============================================================================

pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven("https://maven.kikugie.dev/releases")
        maven("https://maven.kikugie.dev/snapshots")
        maven("https://maven.fabricmc.net/")
        maven("https://maven.architectury.dev")
        maven("https://maven.minecraftforge.net")
        maven("https://maven.neoforged.net/releases/")
    }
}

plugins {
    id("gg.meza.stonecraft") version "1.10.+"
    id("dev.kikugie.stonecutter") version "0.9.+"
    // Auto-downloads the JDK toolchains required by each version group
    // (17 for G1, 21 for G2, 25 for G3) when they are not installed locally.
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

stonecutter {
    centralScript = "build.gradle.kts"
    kotlinController = true
    shared {
        // Register a (minecraft version, loader) variant for every released jar.
        fun mc(version: String, vararg loaders: String) {
            for (it in loaders) version("$version-$it", version)
        }

        mc("1.18.2", "fabric", "forge")          // G1: authcore-1.16-1.18-{fabric,forge}
        mc("1.21.11", "fabric", "forge", "neoforge") // G2: authcore-1.19-1.21-{fabric,forge,neoforge}
        mc("26.2", "fabric", "neoforge")         // G3: authcore-26.1-26.2-{fabric,neoforge}

        // The default version used by IDEs and bare `gradlew` invocations.
        vcsVersion = "1.21.11-fabric"
    }
    create(rootProject)
}

rootProject.name = "AuthCore"
